### PR TITLE
Feature/header footer

### PR DESCRIPTION
**Pull request by tibvdm**
Adresses the header and the footer of the web application. 
Branches from #3, so cannot be merged yet.

### CODE REVIEW

**Comment by tibvdm** [comment]
image

image
image

**Review by pverscha — CHANGES_REQUESTED** [review]
There's one thing missing from the footer. For each page (or part) of the web application, we add the relevant publication to the footer such that users of our software are encouraged to cite the correct article when they use a specific portion of Unipept.

In order to improve readability of the footer, I would therefor suggest to increase its height and move the "mail", "twitter" and "github" icons up so that they appear above the "Terms of service" and "News" links. On the left side of the footer we could then add a link to the relevant publication. A listing of all publications and the relevant pages to include them can be found here:

* Homepage, tryptic peptide analysis and metaproteomics analysis: `Gurdeep Singh et al. (2019) Journal of Proteome Research https://doi.org/10.1021/acs.jproteome.8b00716`
* API and CLI documentation: `Verschaffelt et al. (2020) Bioinformatics https://doi.org/10.1093/bioinformatics/btaa553`
* Metagenomics documentation: `Van der Jeugt et al. (2022) BMC Genomics https://doi.org/10.1186/s12864-022-08542-4`
* Unipept Desktop documentation: `Verschaffelt et al. (2021) Journal of Proteome Research https://doi.org/10.1021/acs.jproteome.0c00855`

We can store this information in the routes and render the correct link to the correct publication according to the current route. See [this](https://github.com/unipept/unipept-desktop/blob/e3348d96701f4542ed9cdeb3da10fc19c3a92248/src/main.ts#L64) link for an example of how to encode this information in the routes and [this](https://github.com/unipept/unipept-desktop/blob/e3348d96701f4542ed9cdeb3da10fc19c3a92248/src/App.vue#L6) for how to retrieve this information from the router.

**Comment by pverscha** [comment]
This is how it's done by the current web application: 
image

**Comment by tibvdm** [comment]
Updated header:
image

Updated footer:
image

image

**Review by pverscha — APPROVED** [review]
I further improved the contrast of the navbar items in the header, but all looks good now! Thanks :D

**Comment by pverscha** [comment]
Image of the header as it is right now:

image

**Pull request merged**
