### PR TITLE
Feature/about page

### PR DESCRIPTION
**Pull request by tibvdm**

### CODE REVIEW

**Review by pverscha — APPROVED** [review]
Looks good :) Maybe we can make the elixir logo a little smaller? I feel like it's a little bit displaced here? I'm going to approve this PR anyway, this is just something you might play around with a little more before merging it in develop.

**Comment by pverscha** [comment]
Ah, sidenote, maybe we should add all former master students? This is a list of all people that worked on Unipept over the years:

2013-2014: Toon Willems: Evolutionary reconstruction of the bacterial peptidome through
clustering
2014-2015: Tom Naessens: From metagenome to metaproteome
2015-2016: Stijn Seghers: Advanced index structures for use in the Unipept metagenomics pipeline
2015-2016: Kevin Velghe: Functional analysis of the human metaproteome
2016-2017: Aranka Steyaert: Alternative strategies for gene prediction in the Unipept
Metagenomics Analysis Pipeline
2016-2018: Niels De Graef: Consolidating and Benchmarking the Unipept Metagenomics Analysis
Pipeline

**Comment by tibvdm** [comment]
Screenshot 2023-01-23 at 13 58 15

I also reduced the image size of the sponsors

**Comment by tibvdm** [comment]
Screenshot 2023-01-23 at 14 27 30

**Pull request merged**
