### PR TITLE
Feature/GitHub communication

### PR DESCRIPTION
**Pull request by tibvdm**
Fetch release notes from github and display on the 'News' page. Adds latest news to the homepage

### CODE REVIEW

**Comment by tibvdm** [comment]
image
image

**Comment by pverscha** [comment]
We have discussed this orally, but for future reference, I will post our discussion here.

* On the homepage, we will replace the "news" card with a card that lists the most recent version of each Unipept-tool (i.e. API, CLI, Desktop and Web). Each of these tools will then link to a listing of the releases for the corresponding tool (in the same style that's currently being used to render the changelogs). 
* For the releases and changelogs, we will update the "news"-section such that it consists of 5 different subpages. The first page is an overview that displays the most recent release (including the changelog) for each of the 4 major Unipept tools. Then, we create a page per tool that shows the changelogs of the 5 most recent releases of this component.
* Each of the release cards links to the corresponding release page on GitHub.

**Review by pverscha — CHANGES_REQUESTED** [review]
We have discussed this orally, but for future reference, I will post our discussion here.

* On the homepage, we will replace the "news" card with a card that lists the most recent version of each Unipept-tool (i.e. API, CLI, Desktop and Web). Each of these tools will then link to a listing of the releases for the corresponding tool (in the same style that's currently being used to render the changelogs). 
* For the releases and changelogs, we will update the "news"-section such that it consists of 5 different subpages. The first page is an overview that displays the most recent release (including the changelog) for each of the 4 major Unipept tools. Then, we create a page per tool that shows the changelogs of the 5 most recent releases of this component.
* Each of the release cards links to the corresponding release page on GitHub.

**Comment by tibvdm** [comment]
**Note: This PR will have to wait for** #5

**Comment by tibvdm** [comment]
Homepage versions:
image
Homepage versions (small):
image
News overview (small):
image
API news:
image

**Review by pverscha — CHANGES_REQUESTED** [review]
* [x] A few things are still being logged to the console (I can see some numbers appearing in the console after loading the webpage).
* [x] I think things look better if we remove the top margin of the releases card. So that it looks like the second screenshot (the first one is what it looks like now).
Before:
image

After:
image

* [x] Remove the "dots" from the unordered lists in these cards (such that improved, fixed, etc) are the first items on each row.
image

* [x] Capitalize list items in the navbar on the right. (overview -> Overview, api -> API, cli -> CLI, web -> Web, desktop -> Desktop).
image

**Comment by pverscha** [comment]
The capitalization of the items in the sidebar is not completely correct yet ;) (Api --> API, Cli --> CLI, the others are fine!)

image

**Review by pverscha — CHANGES_REQUESTED** [review]
See previous comment for the requested changes :)

**Review by pverscha — APPROVED** [review]
All looks good now!

**Pull request merged**
